import puppeteer from "puppeteer";
const bA = await puppeteer.launch({ headless: true, args: ["--no-sandbox"], protocolTimeout: 90000 });
const bB = await puppeteer.launch({ headless: true, args: ["--no-sandbox"], protocolTimeout: 90000 });
const host = await bA.newPage();
const guest = await bB.newPage();
host.on("console", m => { const t = m.text(); if (t.includes("[trace]") || m.type()==="error") console.log("HOST: " + t.slice(0,120)); });
guest.on("console", m => { const t = m.text(); if (t.includes("[trace]") || m.type()==="error") console.log("GUEST: " + t.slice(0,120)); });
const URL = "http://localhost:4173/?relays=ws://127.0.0.1:4748";
await host.goto(URL, { waitUntil: "networkidle2", timeout: 60000 });
await host.click("#btn-online"); await host.waitForSelector("#lobby", { timeout: 10000 });
await host.type("#lobby-name", "Host"); await host.click("#btn-host");
await host.waitForFunction(() => (document.querySelector("#lobby-invite")?.textContent || "").includes("Invite code"), { timeout: 30000 });
const code = (await host.$eval("#lobby-invite", el => el.textContent)).match(/Invite code:\s*(\S+)/)[1];
await guest.goto(URL, { waitUntil: "networkidle2", timeout: 60000 });
await guest.click("#btn-online"); await guest.waitForSelector("#lobby", { timeout: 10000 });
await guest.type("#lobby-name", "Guest"); await guest.type("#lobby-code", code); await guest.click("#btn-join");
await new Promise(r => setTimeout(r, 12000));
await bA.close(); await bB.close();
process.exit(0);
